### ISSUE TITLE
Typo error

### ISSUE THREAD

**Issue by ansidev** [hex-digital/nuxt-intercom#1]
https://github.com/hex-digital/nuxt-intercom/blob/1c7135278391bfb4beddf2942f2724552e4f4052/lib/module.js#L33

It must be `ssr` (**s**erver **s**ide **r**endering).

Ref link: https://nuxtjs.org/api/internals-module-container/#addplugin-template-

**Comment by Jamiewarb** [comment]
Thanks a lot for this!

**Comment by Jamiewarb** [comment]
This is fixed in v0.0.5

**Comment by jhull** [comment]
Sry to bring this up again - but does this support SSR/generate for Nuxt?

**Comment by Jamiewarb** [comment]
Yes, it's being used on https://whirli.com

**Comment by jhull** [comment]
Got it to work. 😃 (and it does work with full static). Thanks!
