### ISSUE TITLE
Intercom not showing

### ISSUE THREAD

**Issue by muresanandrei1** [hex-digital/nuxt-intercom#10]
Hi, sometimes intercom is not booting up properly, not showing up, with debug on this is what i see in the console

![image](https://user-images.githubusercontent.com/23735853/92609420-37f99400-f2bf-11ea-977c-a245c666191c.png)

I am running the app in dev mode, I tried looking at your example but that is in SPA mode, I need to run mine in SSR, can I provide any other info? thanks!

**Comment by muresanandrei1** [comment]
Found the problem.

I am also using @nuxtjs/prismic module which - for some reason - removes intercom widget from the DOM...

I will close this, sorry for the trouble

**Comment by asencis** [comment]
@muresanandrei1 Hi Muresan, could you advise on what you found ... we're also using the prismic module and it seems to also be removing the intercom widget from the DOM on update...
