### ISSUE TITLE
Hide Intercom App per Page

### ISSUE THREAD

**Issue by jhull** [hex-digital/nuxt-intercom#12]
Am I missing something super obvious? Is there a way to not load the Intercom app on certain pages? I've got a mix of content and app related material, and would like to reserve it for the latter.

**Comment by ooOsH** [comment]
There is a way with the intercom SDK, wondering if this would work?

https://gist.github.com/JackGJenkins/b8160e3f237c8d7ea836af83d1a6db09

**Comment by Jamiewarb** [comment]
Hey! I don't think there is a way to not load it per page, but you can hide it on particular pages, similar to the link @ooOsH has posted.

I imagine beforeMount of the page component would be a good place for it, or a hook in the router

**Comment by ooOsH** [comment]
Does the plugin inject intercom into the context?

**Comment by Jamiewarb** [comment]
Yep
https://github.com/hex-digital/nuxt-intercom/blob/master/lib/plugin.js#L12

**Comment by ooOsH** [comment]
> Yep
> https://github.com/hex-digital/nuxt-intercom/blob/master/lib/plugin.js#L12

This doesn't seem to work I get an error when trying to use within a hook in my template

`this.$intercom is not a function`
