### ISSUE TITLE
How to provide App ID dynamically, not via the nuxt.config? 

### ISSUE THREAD

**Issue by koresar** [hex-digital/nuxt-intercom#13]
Hello.
Thank you for the nice plugin.

We have few sites with a single code base.
Is there a way to provide App ID dynamically, not via the nuxt.config?

**Comment by Jamiewarb** [comment]
Hey @koresar 

I think the most sensible solution for you would be to put the ID into a .env file, and use Nuxt’s publicRuntimeConfig key. This will allow you to set a different ID per environment. We do this for the same use case as you and it works great. 

Alternatively, you can use a function in place of the ID which resolves on module load. You could use this to make an API call to get the ID. 

See: https://github.com/hex-digital/nuxt-intercom/blob/master/lib/module.js

**Comment by koresar** [comment]
Ah. Forgot to tell very important detail.
The App ID is fetched during the app start from the server.

But I like your second suggestion. The module load happens in build time, in the browser. Correct?

**Comment by Jamiewarb** [comment]
I think so, yeah. Let me know if it doesn't seem to work for you though

**Comment by koresar** [comment]
It should work. Thanks for your help.

**Comment by koresar** [comment]
Well... it didn't work for us. We deploy same exact (zip) bundle to
different domains. But that's okay. We have a workaround.
