### ISSUE TITLE
this.$intercom is not a function

### ISSUE THREAD

**Issue by asencis** [hex-digital/nuxt-intercom#17]
So, when attempting to access this.$intercom from within layouts or components, nuxt is throwing the above error.

I have it set up exactly as the documentation explains.

I have ensured my id is correct (when removing the offending code, Intercom springs into life). However, I need to update for the active user in my applicartion when they log in ...

**Comment by asencis** [comment]
@Jamiewarb Hi Jamie, sorry to pester. Are you able to offer any advise for the above issue?

I'm specifically looking to update the intercom package when a user is authenticated through our system... specifically when we call something like, `this.$intercom('update', someUserObj)` the system throws a not a function error. We have also tried `this.$intercom.update()` as well ... but not luck their either.

Any tips you could provide would be amazing! Thank you

**Comment by Jamiewarb** [comment]
Hey @asencis 

Sorry to hear it's not working for you, I'd love to help fix! Are you able to share with me a small reproduction repo with instructions to reproduce? That'll allow me to spin it up with your exact problem and help find the cause

Thanks!

**Comment by asencis** [comment]
Hi @Jamiewarb I can't I'm afraid - it's quite the complex application. :/

The simplest reproduction would be to do the following:

1. Create a new nuxt application.
2. Install intercom as per your instructions within the documentation.
3. Call this.$intercom('update', params) where params is:

```js
let params = {
    'appId': process.env.MY_INTERCOM_ID
}
```

Without the `this.$intercom('update', params)` line - Intercom boots absolutely fine.

Inspection of this.$intercom essentially does not expose a method for updating ... and looking through the source code I'm not sure we can overide a class initialisation from the instance ...

**Comment by Jamiewarb** [comment]
Thanks for that! Would you be able to spin that up in a repo and send me a link? Then I can clone it and see what's happening for you

**Comment by asencis** [comment]
@Jamiewarb Will try and get round to this ASAP. Thank you!

**Comment by asencis** [comment]
Hi @Jamiewarb , just a quick one as we might be able to fix but can I ask what the usage of this.$intercom on the component level? What do we have available etc, and within which lifecycle hooks etc etc

**Comment by Jamiewarb** [comment]
Should be injected by Nuxt
https://nuxtjs.org/docs/2.x/directory-structure/plugins/#inject-in-root--context

**Comment by asencis** [comment]
@Jamiewarb 

So we're using `this.$intercom('update', params)` inside a method, which is called by a watcher which is watching for when the user object changes ...

**Comment by Jamiewarb** [comment]
It's a bit difficult to diagnose from just that as there's a few different places that it could be going wrong. Are you able to put a reproduction together?

`this.$intercom` should be injected into all Vue components clientside, the context serverside, and vuex stores. The following examples from Nuxt's docs on context would apply to `this.$intercom`:

```js
export default {
  mounted() {
    console.log(this.$intercom);
  },
  asyncData({ app, $intercom }) {
    $intercom.boot();
  },
};
```

```js
export const state = () => ({
  user: null,
})

export const actions = {
  setUserValueToWhatever(context, user) {
    this.$intercom.update(user);
  }
}
```

Available methods to call are here: https://github.com/hex-digital/nuxt-intercom/blob/master/lib/Intercom.js

If you want to make raw calls to the intercom object, and bypass this plugin's abstraction, call either `window.Intercom` or `this.$intercom.call()

**Comment by asencis** [comment]
@Jamiewarb Hi Jamie, so following your guide, we're not seeing the error.

Could you give us a some more info on what the user looks like, for example, we're just passing in the inetrcom defined user object, so `name` and `user_id` ... i.e. `user = { name: '...', user_id: '...' }`. Then we call: this.intercom.update(user)...however, we can no longer see the intercom widget ...

We have called `this.$intercom.boot()` directly after we update the user ... but nothing ....

We've also tried this:

```
this.$intercom.update({ user: this.intercomUser })
this.$intercom.boot()
```

...where this.intercomUser is `{ name: '...', user_id: '...' }`.

Both yield no widget ...

**Comment by asencis** [comment]
Also, the example for the mounted lifecycle hook does not work, we receive this error:

```
Cannot find Intercom object on window. Make sure Intercom loaded correctly.
```

**Comment by Jamiewarb** [comment]
Thanks for the detail mate.

The plugin doesn't do a whole lot extra for you out of the box, so the best how to use guide would be Intercom's own documentation.

This plugin just:

- Creates a placeholder object to store events called during SSR, and then sends those events once client-side hydration has taken over
- Adds the Intercom script to the page once on mounted 
- Calls `$intercom.init()`
- Calls `$intercom.boot()` if `autoboot` is true
- Starts page tracking if `pageTracking` is true - page tracking is just an `$intercom.update()` call added to the ctx.app.router.afterEach event

It doesn't do a whole lot else - you can see it in all in https://github.com/hex-digital/nuxt-intercom

Intercom's documentation should then guide you for your application specific logic, such as when to update the user object, and what with.

If you disagree, let me know, as it would be good to improve this where we can. If you are able to write something without domain or application logic in to help explain to others some use cases, that would be super useful as well.

**Comment by asencis** [comment]
Hi @Jamiewarb ok so I probably need to close this now, I'm asking for a reproducable example of which calls to make and when we need to update a user. Nothing seems to be working, auto boot is also failing 9 times out of 10. 

We simply want it to auto boot on first load (which it is failing to do so), and when the user changes we want to update $intercom with the userData needed or some default value...

**Comment by SamnangChhuon** [comment]
> Also, the example for the mounted lifecycle hook does not work, we receive this error:
> 
> ```
> Cannot find Intercom object on window. Make sure Intercom loaded correctly.
> ```

I had seen your problem facing similar to what I faced. I tried many ways and I found one way which I just add intercom.js as the script in the head of the application and the error was gone.

intercom.js
`//Set your APP_ID
var APP_ID = "APP_ID";

(function(){var w=window;var ic=w.Intercom;if(typeof ic==="function"){ic('reattach_activator');ic('update',w.intercomSettings);}else{var d=document;var i=function(){i.c(arguments);};i.q=[];i.c=function(args){i.q.push(args);};w.Intercom=i;var l=function(){var s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://widget.intercom.io/widget/' + APP_ID;var x=d.getElementsByTagName('script')[0];x.parentNode.insertBefore(s, x);};if(document.readyState==='complete'){l();}else if(w.attachEvent){w.attachEvent('onload',l);}else{w.addEventListener('load',l,false);}}})();`

Got from: https://developers.intercom.com/installing-intercom/docs/basic-javascript

Hope it can help.
