### ISSUE TITLE
Add live demo site

### ISSUE THREAD

**Issue by ansidev** [hex-digital/nuxt-intercom#2]
I think you should have a live demo site.

Netlify can do that.

**Comment by Jamiewarb** [comment]
Good idea, will get a demo up shortly.

**Comment by Jamiewarb** [comment]
Only problem I seem to have is that Intercom doesn't have a free tier, and without a valid appId the widget won't display.

Perhaps some videos demonstrating its use in the README may work. What do you think?

**Comment by ansidev** [comment]
Maybe.

**Comment by Jamiewarb** [comment]
Ah, I can use the appId of the widget on Intercom's main website, so I'll use that and get a demo up now.

**Comment by Jamiewarb** [comment]
That's been added to the top of the README now. Thanks for the suggestion!
