### ISSUE TITLE
How can I update user data with this module?

### ISSUE THREAD

**Issue by rahulrumalla** [hex-digital/nuxt-intercom#3]
Trying to work out how to access the `intercom` module throughout the app. Particularly in nuxt store. I'm mainly looking to update the user data once logged in and do a shutdown when the session ends. Any examples for this, please?

**Comment by Jamiewarb** [comment]
So this module exposes a `this.$intercom` object, which is the `Intercom` object from the intercom docs.

So any function here (https://developers.intercom.com/installing-intercom/docs/intercom-javascript) that uses `Intercom` can be done using `this.$intercom`

**Comment by rahulrumalla** [comment]
Thanks for responding @Jamiewarb 

I'm having a pretty strange issue where the app complains that the `this.$intercom` is not defined. Another strange thing I have noticed is that it does work but almost at random. I notice that intercom shows up when once in 5-10 times when I refresh the page. 

Here's my nuxt config flile
```
module.exports = {
  /*
  ** Headers of the page
  */
  head: {
    title: 'Nuxt + intercom',
    meta: [
      {charset: 'utf-8'},
      {name: 'viewport', content: 'width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui'},
      {hid: 'description', name: 'description', content: 'Nuxt.js project'}
    ],
    link: [
      {rel: 'icon', type: 'image/x-icon', href: '/favicon.ico'}
    ],
    script: [
      { src: 'https://js.stripe.com/v3/' }
    ],
  },
  /*
  ** Customize the progress-bar color
  */
  loading: {color: '#3B8070'},
  /*  
  ** Build configuration
  */
  mode: 'spa',
  buildModules: [
    '@nuxtjs/gtm',
    '@hexdigital/nuxt-intercom',
  ],
  gtm: {
    id: process.env.GTM,
    dev: !(process.env.NODE_ENV === 'production'),
    pageTracking: true,
    autoInit: true,
    respectDoNotTrack: false,
  },

  intercom: {
    appId: 'l6lwr2s5',
    autoBoot: true, 
    debug: true,
    // scriptId: 'intercom-script',
    // scriptDefer: false,
    // updateOnPageRoute: false
  },

  build: {
    // vendor: [
    //   'vuetify',
    //   'axios',
    //   'js-cookie',
    // ],
    extractCSS: true,
    /*
    ** Run ESLINT on save
    */
    extend (config, ctx) {
      if (ctx.isDev && process.client) {
        config.module.rules.push({
          enforce: 'pre',
          test: /\.(js|vue)$/,
          loader: 'eslint-loader',
          exclude: /(node_modules)/
        })
      }
    }
  },
  /*
  ** Router configuration
   */
  router: {
    middleware: 'check-auth'
  },
  serverMiddleware: [
    'redirect-ssl'
  ],
  plugins: [
    '~plugins/vuetify.js',
    '~plugins/axios.js',
    {src: '~plugins/vue-echarts.js', ssr: false},
    // {src: '~plugins/flag.js', ssr: false},
  ],
  css: [
    '~/assets/style/app.styl',
    '~/assets/style/fonts.styl' 
  ],
  srcDir: 'src/',
  rootDir: './'
}
```

I do see the intercom logs in console though. But the intercom messenger itself shows up at random when I refresh the page
![image](https://user-images.githubusercontent.com/1197049/82030169-5a283000-9698-11ea-95d2-6ec8c95b4d7e.png)

When it does work, I do see the `ping` call to api.intercom. But this requests never happens most of the time I refresh the page
![image](https://user-images.githubusercontent.com/1197049/82030762-27326c00-9699-11ea-832c-945904ec3763.png)

I suspect that intercom is not getting booted on every refresh for some reason. 

Any suggestions on how I could diagnose this further, please?

**Comment by Jamiewarb** [comment]
Thanks for the report - are you able to send me a link to the repo, or set up a test repo that has the same problem so I can look in to it?

**Comment by rahulrumalla** [comment]
Hello. Thanks for extending help. While I was setting up a bare repo for you, I was able to figure it out. The problem was with using axios as a plugic with a custom interceptor configured on it. I migrated to using the community module @nuxt/axios and everything worked like a charm. Although not exactly sure what was causing the original issue though . 

Thanks, again :D

**Comment by Jamiewarb** [comment]
Very strange. Glad you solved it!
