### ISSUE TITLE
Is Nuxt 3 supported?

### ISSUE THREAD

**Issue by kaydwithers** [hex-digital/nuxt-intercom#33]
I'm trying to integrate nuxt-intercom into my Nuxt 3 App, however I get the error..

`Cannot start nuxt:  appId is not defined`

**Comment by Jamiewarb** [comment]
No this hasn't been updated for a Nuxt 3

**Comment by kaydwithers** [comment]
@Jamiewarb Are there any plans on updating it to work with Nuxt 3?

**Comment by Jamiewarb** [comment]
Unfortunately not at this time. Thinking about it, I will reopen the issue and we'll put Nuxt 3 support on the roadmap, but I can't give a date for it and we're not actively working on it right now.

We'll likely revisit it sometime after Nuxt 3 has been released. Alternatively, if you or others are happy to update for Nuxt 3 we'd be extremely grateful and happy to accept a PR.

**Comment by JulzPolz** [comment]
Has this been completed yet? Nuxt 3 has been out for quite some time now. Lots of sites have moved over to it and have had to move away from Intercom due to no support for it.

**Comment by Jamiewarb** [comment]
Hi mate,
We haven't had the need to use this module on a Nuxt 3 site, and so haven't upgraded it for now.
If you or others are happy to update for Nuxt 3 we'd be extremely grateful and happy to accept a PR.

**Comment by devonik** [comment]
Why it's shown on the nuxt3 modules page then ? ... https://nuxt.com/modules/intercom

**Comment by elizabthpazp** [comment]
This module would be very good in nuxt 3🥺

**Comment by Jamiewarb** [comment]
Thanks for that. I'll close this issue and point others to this repo for Nuxt 3
