### ISSUE TITLE
How to hide plugin after boot?

### ISSUE THREAD

**Issue by ChucKN0risK** [hex-digital/nuxt-intercom#4]
I would like to hide the plugin once it's ready.

I created a `intercom.js` file but the intercom instance is not ready in this context.

```
export default function (context) {
  // Can't work since intercom.ready === false :/
  context.app.$intercom.boot();
  context.app.$intercom.hide();
}
```

My `nuxt.config.js`:
```
{
  plugins: [
    { src: '~/plugins/intercom.js', mode: 'client' },
  ]
  buildModules: [
    '@hexdigital/nuxt-intercom',
  ],
  intercom: {
    appId: 'XXXXXXXXXX',
    autoBoot: false,
  },
}
```

I get the following error:
```
Error: "Cannot find Intercom object on window. Make sure Intercom loaded correctly."
    NuxtJS 2
    default intercom.js:6
    _callee2$ NuxtJS
    tryCatch runtime.js:45
    invoke runtime.js:274
    method runtime.js:97
    node_modules asyncToGenerator.js:5
    node_modules asyncToGenerator.js:27
```

**Comment by Jamiewarb** [comment]
Ah, you'll likely need to use `autoBoot: false`, then boot it manually in a plugin and add whatever logic you need there

**Comment by ChucKN0risK** [comment]
Yes this is what I did but in my plugin `intercom.js` the intercom instance has its ready property to false. This is why I have the error `"Cannot find Intercom object on window. Make sure Intercom loaded correctly."` I think.

**Comment by Jamiewarb** [comment]
You may need to call `init()` instead of `boot()`.

You'll also need to make sure intercom has loaded already.

This file is how this module does that: https://github.com/hex-digital/nuxt-intercom/blob/master/lib/plugin.js

**Comment by ChucKN0risK** [comment]
> Ah apologies, I can see the plugin will call init() itself, but this is only once Intercom has loaded.
Seems logical to me ;)

> Your snippet above looks like it's in a Nuxt plugin, so you'll need to make sure intercom has loaded already before calling boot.
Yes it is a Nuxt plugin. But the root of my issue is that I don't know how to detect when Intercom has loaded. I can access to the instance thanks to `context.app.intercom` but I can't call any methods since window doesn't have any Intercom object.

I don't understand how your module could help me because to my eyes it is part of your plugin configuration. The only idea I have is to add in the configuration a `afterInit` hook.

**Comment by Jamiewarb** [comment]
Yeah perhaps a hook like that would work well here. If you'd like to submit a PR, I can prioritise reviewing it and getting it released, otherwise I may be able to add it over the weekend

**Comment by ChucKN0risK** [comment]
OK I'll submit a PR. Thanks a lot for your help ;)

**Comment by ChucKN0risK** [comment]
In fact I won't submit a PR. I'll go with the native Intercom script 😉
